---
# tasks file for install_docker

- name: Install Docker in RedHat
  block:
    - name: Remove old docker
      yum:
        name:
          - docker
          - docker-client 
          - docker-client-latest
          - docker-common
          - docker-latest
          - docker-latest-logrotate
          - docker-logrotate
          - docker-engine
        state: absent

    - name: Install yum-utils
      yum:
        name: yum-utils
        state: latest

    - name: Add repository
      shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
      args:
        creates: /etc/yum.repos.d/docker-ce.repo

    - name: Install docker engine
      yum:
        name: 
          - docker-ce
          - docker-ce-cli
          - containerd.io

    - name: Create directory
      file:
        path: /etc/docker
        state: directory
        owner: root
        group: root
        mode: 0755

    - name: Copy config daemon.json
      copy: 
        src: "{{ src_file }}"
        dest: "{{ dest_file }}"

    - name: Start docker
      systemd:
        name: docker
        state: started
        enabled: yes 
  when: ansible_os_family == "RedHat"


- name: Install Docker in Debian
  block:
    - name: Remove old docker
      apt:
        name:
          - docker
          - docker-engine
          - docker.io
          - containerd
          - runc
        state: absent

    - name: Update packages
      command: apt-get update -y

    - name: Set up the repository
      apt:
        name: 
          - ca-certificates
          - curl
          - gnupg 
          - lsb-release
        state: latest

    - name: Add Docker official GPG key
      shell: curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
      args:
        creates: /usr/share/keyrings/docker-archive-keyring.gpg

    - name: Set up the stable repository
      shell: echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
      args:
        creates: /etc/apt/sources.list.d/docker.list

    - name: Update packages
      command: apt-get update -y

    - name: Install Docker Engine
      apt:
        name: 
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: latest

    - name: Copy config daemon.json
      copy: 
        src: "{{ src_file }}"
        dest: "{{ dest_file }}"

    - name: Start docker
      systemd:
        name: docker
        state: started
        enabled: yes 
  when: ansible_os_family == "Debian"
