---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: centos7
    image: solita/centos-systemd:7
    command: /sbin/init
    privileged: True
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
   
  - name: debian10
    image: alehaa/debian-systemd:buster
    command: /sbin/init
    privileged: True
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"

  - name: ubuntu18
    image: solita/ubuntu-systemd:18.04
    command: /sbin/init
    privileged: True
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"

provisioner:
  name: ansible
verifier:
  name: ansible
